[package]
name = "gonkboard"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
poem = { version = "1.3.40", features = ["session"] }
serde = { version = "1.0.144", features = ["derive"] }
tokio = { version = "1.21.0", features = ["macros", "rt-multi-thread"] }
tracing-subscriber = { version = "0.3.15", features = ["env-filter"] }
