[package]
name = "synalpheus"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
lazy_static = "1.4.0"
oauth2 = "4.2.3"
poem = { version = "1.3.40", features = ["session", "csrf", "redis-session"] }
redis = "0.21.6"
reqwest = { version = "0.11.11", features = ["json"] }
serde = { version = "1.0.144", features = ["derive"] }
tera = "1.17.0"
tokio = { version = "1.21.0", features = ["macros", "rt-multi-thread"] }
tracing-subscriber = { version = "0.3.15", features = ["env-filter"] }
