[package]
name = "synalpheus"
version = "0.2.5"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
futures = { version = "0.3", features = ["executor"] }
oauth2 = "4"
once_cell = "1.17"
poem = { version = "1.3", features = [
    "session",
    "csrf",
    "redis-session",
    "test",
] }
# For some reason redis 0.23 doesn't build at the moment
redis = { version = "0.22", features = [
    "aio",
    "tokio-comp",
    "connection-manager",
] }
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1", features = ["std"] }
tera = "1.18"
tokio = { version = "1.28", features = ["macros", "rt-multi-thread"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
url = "2.3"
