name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
      env:
        SYN_AUTHENTIK_URL: auth.local
        SYN_REDIRECT_PATH: /auth/authentik
        SYN_CLIENT_ID: 1234
        SYN_CLIENT_SECRET: 4321
        SYN_REDIRECT_URL: http://localhost/auth/authentik
